name: Deploy changes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
      - name: Install dependencies
        run: npm install    
      - name: Generate build
        run: npm run build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: react-github-actions-build
          path: build/build
  deploy:
    runs-on: ubuntu-latest
    # When application is successfully tested and build has been generated
    # Then we can start with deployment
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: react-github-actions-build
      # Set the credentials from repository settings/secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # Copy the files from build folder to the S3 bucket
      - name: Check contents of build folder
        run: ls /home/runner/work/rubble-mag/rubble-mag && ls /home/runner/work/rubble-mag/rubble-mag/static
      - name: Deploy static site to root S3 bucket
        run: aws s3 sync . s3://sarahconlisk.com --delete
        working-directory: react-github-actions-build
      - name: Invalidate cached files in Cloudfront
        run: aws cloudfront create-invalidation --paths "/*" --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
